---
- name: Build and Run Docker Image
  hosts: production-srv
  become: yes

  tasks:
  - name: Pull change
    ansible.builtin.shell:
      chdir: /home/Simple-Go-Web
      cmd: git pull origin main

  - name: Run docker-compose build
    ansible.builtin.shell:
      chdir: /home/Simple-Go-Web
      cmd: docker-compose build --no-cache

  - name: Run Container
    ansible.builtin.shell:
      chdir: /home/Simple-Go-Web
      cmd: docker-compose up -d